/**
 * Example Quiz Module
 * In actual stories, this would be generated by AI based on story content
 */

function initQuiz(containerId) {
  const container = document.getElementById(containerId);
  if (!container) {
    console.error('Quiz container not found');
    return;
  }

  const questions = [
    {
      question: "Where did Alex's family go?",
      options: ["The park", "The mall", "The beach", "The library"],
      correct: 0
    },
    {
      question: "What did Mom pack in the bag?",
      options: ["Toys", "Books", "Snacks and water", "Games"],
      correct: 2
    },
    {
      question: "What did Alex do at the park?",
      options: ["Read a book", "Made a new friend", "Took a nap", "Did homework"],
      correct: 1
    }
  ];

  let currentQuestion = 0;
  let score = 0;

  function renderQuestion() {
    if (currentQuestion >= questions.length) {
      showResults();
      return;
    }

    const q = questions[currentQuestion];
    container.innerHTML = `
      <div class="quiz-question">
        <h3>Question ${currentQuestion + 1} of ${questions.length}</h3>
        <p style="font-size: 1.2rem; margin: 20px 0;">${q.question}</p>
        <div class="quiz-options">
          ${q.options.map((opt, i) => `
            <button class="quiz-option" data-index="${i}">
              ${opt}
            </button>
          `).join('')}
        </div>
      </div>
    `;

    container.querySelectorAll('.quiz-option').forEach(btn => {
      btn.addEventListener('click', (e) => {
        const selected = parseInt(e.target.dataset.index);
        if (selected === q.correct) {
          e.target.classList.add('correct');
          score++;
        } else {
          e.target.classList.add('incorrect');
          container.querySelector(`[data-index="${q.correct}"]`).classList.add('correct');
        }
        setTimeout(() => {
          currentQuestion++;
          renderQuestion();
        }, 1500);
      });
    });
  }

  function showResults() {
    const percentage = (score / questions.length) * 100;
    container.innerHTML = `
      <div class="score-display">
        <h2>Quiz Complete! 🎉</h2>
        <p style="font-size: 2rem; margin: 20px 0;">
          ${score} / ${questions.length}
        </p>
        <p style="font-size: 1.2rem;">
          ${percentage >= 70 ? 'Great job! You understood the story well!' : 'Good try! Try reading the story again.'}
        </p>
        <button class="btn btn-primary" onclick="location.reload()">Try Again</button>
      </div>
    `;
  }

  renderQuestion();
}

// Auto-initialize if container exists
document.addEventListener('DOMContentLoaded', () => {
  if (document.getElementById('quiz-container')) {
    initQuiz('quiz-container');
  }
});

